# Site settings
title: merem.in
email: onto@merem.in
description: > # this means to ignore newlines until "baseurl:"
  Karena merem itu indah.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://merem.in" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
